// Variant classes mapping
import { VariantType } from "@/components/atoms/typography/types";

export const variantClasses: Record<VariantType, string> = {
  xs: "text-xs",
  sm: "text-sm",
  base: "text-base",
  lg: "text-lg",
  xl: "text-xl",
  "2xl": "text-2xl",
  "3xl": "text-3xl",
  "4xl": "text-4xl",
  "5xl": "text-5xl",
  "6xl": "text-6xl",
  "7xl": "text-7xl",
  "8xl": "text-8xl",
  "9xl": "text-9xl",
  "fluid-xs": "text-fluid-xs",
  "fluid-sm": "text-fluid-sm",
  "fluid-base": "text-fluid-base",
  "fluid-lg": "text-fluid-lg",
  "fluid-xl": "text-fluid-xl",
  "fluid-2xl": "text-fluid-2xl",
  "fluid-3xl": "text-fluid-3xl",
  "fluid-4xl": "text-fluid-4xl",
  "fluid-5xl": "text-fluid-5xl",
  "fluid-6xl": "text-fluid-6xl",
  "fluid-7xl": "text-fluid-7xl",
  "fluid-40": "text-fluid-40",
  display: "text-display font-bold",
  heading: "text-heading font-semibold",
  subheading: "text-subheading font-medium",
  caption: "text-caption font-normal",
  overline: "text-overline font-medium uppercase",
};
