export const colors = [
  { value: "#000000", label: "Black" },
  { value: "#333333", label: "Dark Gray" },
  { value: "#666666", label: "Gray" },
  { value: "#999999", label: "Light Gray" },
  { value: "#FFFFFF", label: "White" },
  { value: "#FF0000", label: "Red" },
  { value: "#FF9900", label: "Orange" },
  { value: "#FFFF00", label: "Yellow" },
  { value: "#00FF00", label: "Green" },
  { value: "#00FFFF", label: "Cyan" },
  { value: "#0000FF", label: "Blue" },
  { value: "#9900FF", label: "Purple" },
  { value: "#FF00FF", label: "Magenta" },
  { value: "#FFCC00", label: "Gold" },
  { value: "#FFCC99", label: "Peach" },
  { value: "#FFCCFF", label: "Pink" },
  { value: "#CCFFCC", label: "Mint" },
  { value: "#CCFFFF", label: "Sky" },
  { value: "#CCCCFF", label: "Lavender" },
  { value: "#CC99FF", label: "Lilac" },
  { value: "#CC66FF", label: "Orchid" },
  { value: "#CC33FF", label: "Amethyst" },
  { value: "#CC00FF", label: "Violet" },
  { value: "#FF99FF", label: "Rose" },
  { value: "#FF66FF", label: "Fuchsia" },
  { value: "#FF33FF", label: "Mauve" },
  { value: "#FF00CC", label: "Raspberry" },
  { value: "#FF0099", label: "Bubblegum" },
  { value: "#FF0066", label: "Strawberry" },
  { value: "#FF0033", label: "Cherry" },
  { value: "#FF3300", label: "Tangerine" },
  { value: "#FF6600", label: "Pumpkin" },
];
